/*files defined here are necessary for code generation but are par of c libraries so can not be parsed automatically*/
export const studio_h=[
    {type:'type',subtype:'direct',name:'size_t'},
    {type:'type',subtype:'direct',name:'FILE'},
    {type:'type',subtype:'direct',name:'fpos_t'},
    {type:'value',subtype:'int',name:'NULL'},
    {type:'value',subtype:'int',name:'_IOFBF'},
    {type:'value',subtype:'int',name:'_IOLBF'},
    {type:'value',subtype:'int',name:'_IONBF'},
    {type:'value',subtype:'int',name:'BUFSIZ'},
    {type:'value',subtype:'int',name:'EOF'},
    {type:'value',subtype:'int',name:'FOPEN_MAX'},
    {type:'value',subtype:'int',name:'FILENAME_MAX'},
    {type:'value',subtype:'int',name:'L_tmpnam'},
    {type:'value',subtype:'int',name:'SEEK_CUR'},
    {type:'value',subtype:'int',name:'SEEK_END'},
    {type:'value',subtype:'int',name:'SEEK_SET'},
    {type:'value',subtype:'int',name:'TMP_MAX'},
    {type:'value',subtype:'FILE',name:'stderr'},
    {type:'value',subtype:'FILE',name:'stdin'},
    {type:'value',subtype:'FILE',name:'stdout'},
    {type:'function',name:'fclose'  ,args:[{"type":"FILE *","name":"a"}], returntype:'int'},
    {type:'function',name:'clearerr',args:[{"type":"FILE *","name":"a"}], returntype:'void'},
    {type:'function',name:'feof'    ,args:[{"type":"FILE *","name":"a"}], returntype:'int'},
    {type:'function',name:'ferror'  ,args:[{"type":"FILE *","name":"a"}], returntype:'int'},
    {type:'function',name:'fflush'  ,args:[{"type":"FILE *","name":"a"}], returntype:'int'},
    {type:'function',name:'fgetpos' ,args:[{"type":"FILE *","name":"a"},{"type":"fpos_t *","name":"b"}], returntype:'int'},
    {type:'function',name:'fopen'   ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}], returntype:'FILE *'},
    {type:'function',name:'fread'   ,args:[{"type":"void *","name":"a"},{"type":"size_t","name":"b"},{"type":"size_t","name":"c"},{"type":"FILE *","name":"d"}], returntype:'size_t'},
    {type:'function',name:'freopen' ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"},{"type":"FILE *","name":"c"}], returntype:'FILE *'},
    {type:'function',name:'fseek'   ,args:[{"type":"FILE *","name":"a"},{"type":"long int","name":"b"},{"type":"int","name":"c"}], returntype:'int'},
    {type:'function',name:'fsetpos' ,args:[{"type":"FILE *","name":"a"},{"type":"const fpos_t *","name":"b"}], returntype:'int'},
    {type:'function',name:'ftell'   ,args:[{"type":"FILE *","name":"a"}], returntype:'long int'},
    {type:'function',name:'fwrite'  ,args:[{"type":"const void *","name":"a"},{"type":"size_t","name":"b"},{"type":"size_t","name":"c"},{"type":"FILE *","name":"d"}], returntype:'size_t'},
    {type:'function',name:'remove'  ,args:[{"type":"const char *","name":"a"}], returntype:'int'},
    {type:'function',name:'rename'  ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}], returntype:'int'},
    {type:'function',name:'rewind'  ,args:[{"type":"FILE *","name":"a"}], returntype:'void'},
    {type:'function',name:'setbuf'  ,args:[{"type":"FILE *","name":"a"},{"type":"char *","name":"b"}], returntype:'void'},
    {type:'function',name:'setvbuf' ,args:[{"type":"FILE *","name":"a"},{"type":"char *","name":"b"},{"type":"int","name":"c"},{"type":"size_t","name":"d"}], returntype:'void'},
    {type:'function',name:'tmpfile' ,args:[], returntype:'FILE *'},
    {type:'function',name:'tmpnam'  ,args:[{"type":"char *","name":"a"}], returntype:'char *'},
    {type:'function',name:'fprintf' ,args:[{"type":"FILE *","name":"a"},{"type":"const char *","name":"b"},{"type":"...","name":"c"}], returntype:'int'},
    {type:'function',name:'printf'  ,args:[{"type":"const char *","name":"a"},{"type":"...","name":"b"}], returntype:'int'},
    {type:'function',name:'sprintf' ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"},{"type":"...","name":"c"}], returntype:'int'},
    {type:'function',name:'vfprintf',args:[{"type":"FILE *","name":"a"},{"type":"const char *","name":"b"},{"type":"va_list","name":"c"}], returntype:'int'},
    {type:'function',name:'vprintf' ,args:[{"type":"const char *","name":"a"},{"type":"va_list","name":"b"}], returntype:'int'},
    {type:'function',name:'vsprintf',args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"},{"type":"va_list","name":"c"}], returntype:'int'},
    {type:'function',name:'fscanf'  ,args:[{"type":"FILE *","name":"a"},{"type":"const char *","name":"b"},{"type":"...","name":"c"}], returntype:'int'},
    {type:'function',name:'scanf'   ,args:[{"type":"const char *","name":"a"},{"type":"...","name":"b"}], returntype:'int'},
    {type:'function',name:'sscanf'  ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"},{"type":"...","name":"c"}], returntype:'int'},
    {type:'function',name:'fgetc'   ,args:[{"type":"FILE *","name":"a"}], returntype:'int'},
    {type:'function',name:'fgets'   ,args:[{"type":"char *","name":"a"},{"type":"int","name":"b"},{"type":"FILE *","name":"c"}], returntype:'char *'},
    {type:'function',name:'fputc'   ,args:[{"type":"int","name":"a"},{"type":"FILE *","name":"b"}], returntype:'int'},
    {type:'function',name:'fputs'   ,args:[{"type":"const char *","name":"a"},{"type":"FILE *","name":"b"}], returntype:'int'},
    {type:'function',name:'getc'    ,args:[{"type":"FILE *","name":"a"}], returntype:'int'},
    {type:'function',name:'getchar' ,args:[], returntype:'int'},
    {type:'function',name:'gets'    ,args:[{"type":"char *","name":"a"}], returntype:'char *'},
    {type:'function',name:'putc'    ,args:[{"type":"int","name":"a"},{"type":"FILE *","name":"b"}], returntype:'int'},
    {type:'function',name:'putchar' ,args:[{"type":"int","name":"a"}], returntype:'int'},
    {type:'function',name:'puts'    ,args:[{"type":"cost char *","name":"a"}], returntype:'int'},
    {type:'function',name:'ungetc'  ,args:[{"type":"int","name":"a"},{"type":"FILE *","name":"b"}], returntype:'int'},
    {type:'function',name:'perror'  ,args:[{"type":"const char *","name":"a"}], returntype:'void'}
];
export const stdlib_h=[
    {type:'type',subtype:'direct',name:'size_t'},
    {type:'type',subtype:'direct',name:'wchar_t'},
    {type:'type',subtype:'direct',name:'div_t'},
    {type:'type',subtype:'direct',name:'ldiv_t'},
    {type:'value',subtype:'int',name:'NULL'},
    {type:'value',subtype:'int',name:'EXIT_FAILURE'},
    {type:'value',subtype:'int',name:'EXIT_SUCCESS'},
    {type:'value',subtype:'int',name:'RAND_MAX'},
    {type:'value',subtype:'int',name:'MB_CUR_MAX'},
    {type:'function',returnType:'double'  ,name:'atof'    ,args:[{"type":"const char *","name":"a"}]},
    {type:'function',returnType:'int'     ,name:'atoi'    ,args:[{"type":"const char *","name":"a"}]},
    {type:'function',returnType:'long int',name:'atol'    ,args:[{"type":"const char *","name":"a"}]},
    {type:'function',returnType:'double'  ,name:'strtod'  ,args:[{"type":"const char *","name":"a"},{"type":"char * *","name":"b"}]},
    {type:'function',returnType:'long int',name:'strtol'  ,args:[{"type":"const char *","name":"a"},{"type":"char * *","name":"b"},{"type":"int","name":"c"}]},
    {type:'function',returnType:'void *'  ,name:'calloc'  ,args:[{"type":"size_t","name":"a"},{"type":"size_t","name":"b"}]},
    {type:'function',returnType:'void'    ,name:'free'    ,args:[{"type":"void *","name":"a"}]},
    {type:'function',returnType:'void *'  ,name:'malloc'  ,args:[{"type":"size_t","name":"a"}]},
    {type:'function',returnType:'void *'  ,name:'realloc' ,args:[{"type":"void *","name":"a"},{"type":"size_t","name":"b"}]},
    {type:'function',returnType:'void'    ,name:'abort'   ,args:[{"type":"void","name":"a"}]},
    {type:'function',returnType:'void'    ,name:'voidfn'  ,args:[]},
    {type:'function',returnType:'int'     ,name:'atexit'  ,args:[{"type":"voidfn","name":"a"}]},
    {type:'function',returnType:'void'    ,name:'exit'    ,args:[{"type":"int","name":"a"}]},
    {type:'function',returnType:'char *'  ,name:'getenv'  ,args:[{"type":"const char *","name":"a"}]},
    {type:'function',returnType:'int'     ,name:'system'  ,args:[{"type":"const char *","name":"a"}]},
    {type:'function',returnType:'int'     ,name:'cmpfn'   ,args:[{"type":"const void *","name":"a"},{"type":"const void *","name":"b"}]},
    {type:'function',returnType:'void *'  ,name:'bsearch' ,args:[{"type":"const void *","name":"a"},{"type":"const void *","name":"b"},{"type":"size_t","name":"c"},{"type":"size_t","name":"d"},{"type":"cmpfn","name":"e"}]},
    {type:'function',returnType:'void'    ,name:'qsort'   ,args:[{"type":"void *","name":"a"},{"type":"size_t","name":"b"},{"type":"size_t","name":"c"},{"type":"cmpfn","name":"d"}]},
    {type:'function',returnType:'int'     ,name:'abs'     ,args:[{"type":"int","name":"a"}]},
    {type:'function',returnType:'div_t'   ,name:'div'     ,args:[{"type":"int","name":"a"},{"type":"int","name":"b"}]},
    {type:'function',returnType:'long int',name:'labs'    ,args:[{"type":"long int","name":"a"}]},
    {type:'function',returnType:'ldiv_t'  ,name:'ldiv'    ,args:[{"type":"long int","name":"a"},{"type":"long int","name":"b"}]},
    {type:'function',returnType:'int'     ,name:'rand'    ,args:[{"type":"void","name":"a"}]},
    {type:'function',returnType:'void'    ,name:'srand'   ,args:[{"type":"unsigned int","name":"a"}]},
    {type:'function',returnType:'int'     ,name:'mblen'   ,args:[{"type":"const char *","name":"a"},{"type":"size_t","name":"b"}]},
    {type:'function',returnType:'size_t'  ,name:'mbstowcs',args:[{"type":"schar_t *","name":"a"},{"type":"const char *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'int'     ,name:'mbtowc'  ,args:[{"type":"whcar_t *","name":"a"},{"type":"const char *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'size_t'  ,name:'wcstombs',args:[{"type":"char *","name":"a"},{"type":"const wchar_t *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'int'     ,name:'wctomb'  ,args:[{"type":"char *","name":"a"},{"type":"wchar_t","name":"b"}]},
    {type:'function',returnType:'unsigned long int',name:'strtoul',args:[{"type":"const char *","name":"a"},{"type":"char * *","name":"b"},{"type":"int","name":"c"}]}
];
export const string_h=[
    {type:'type',subtype:'direct',name:'size_t'},
    {type:'value',subtype:'int',name:'NULL'},
    {type:'function',returnType:'void *',name:'memchr'  ,args:[{"type":"const void *","name":"a"},{"type":"int","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'int'   ,name:'memcmp'  ,args:[{"type":"const void *","name":"a"},{"type":"const void *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'void *',name:'memcpy'  ,args:[{"type":"void *","name":"a"},{"type":"const void *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'void *',name:'memmove' ,args:[{"type":"void *","name":"a"},{"type":"const void *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'void *',name:'memset'  ,args:[{"type":"void *","name":"a"},{"type":"int","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'char *',name:'strcat'  ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strncat' ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'char *',name:'strchr'  ,args:[{"type":"const char *","name":"a"},{"type":"int","name":"b"}]},
    {type:'function',returnType:'int'   ,name:'strcmp'  ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'int'   ,name:'strncmp' ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'int'   ,name:'strcoll' ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strcpy'  ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strncpy' ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"},{"type":"size_t","name":"c"}]},
    {type:'function',returnType:'size_t',name:'strcspn' ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strerror',args:[{"type":"int","name":"a"}]},
    {type:'function',returnType:'size_t',name:'strlen'  ,args:[{"type":"const char *","name":"a"}]},
    {type:'function',returnType:'char *',name:'strpbrk' ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strrchr' ,args:[{"type":"const char *","name":"a"},{"type":"int","name":"b"}]},
    {type:'function',returnType:'size_t',name:'strspn'  ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strstr'  ,args:[{"type":"const char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'char *',name:'strtok'  ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"}]},
    {type:'function',returnType:'size_t',name:'strxfrm' ,args:[{"type":"char *","name":"a"},{"type":"const char *","name":"b"},{"type":"size_t","name":"c"}]},
];
export const stdarg_h=[
    {type:'type',subtype:'direct',name:'va_list'},
    {type:'function',returnType:'void',name:'va_start',args:[{"type":"va_list","name":"a"}]},
    {type:'function',returnType:'type',name:'va_arg'  ,args:[{"type":"va_list","name":"a"},{"type":"type","name":"b"}]},
    {type:'function',returnType:'void',name:'va_end'  ,args:[{"type":"va_list","name":"a"}]},
    {type:'function',returnType:'void',name:'va_copy' ,args:[{"type":"va_list","name":"a"},{"type":"va_list","name":"b"}]},
];