name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true

    - name: Build
      run: |
        mkdir ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        make -j$(getconf _NPROCESSORS_ONLN)
        mv rayjs.exe ${{github.workspace}}/rayjs.exe
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rayjs
        path: rayjs
  
  deploy:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rayjs
          path: build
