name: Weekly Build

on:
  schedule:
    - cron: "0 3 * * 0"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
        
    - name: Install libs
      run: |
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rayjs-linux
        path: rayjs
        
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rayjs-macos
        path: rayjs
        
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
        
    - name: Configure CMake
      run: cmake -G "MinGW Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rayjs-windows
        path: rayjs.exe
