name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true
        - name: MinGW Winlibs

    - name: Build
      uses: Denzy7/action-mingw@v0.1
      # Build your program with the given configuration
      run: |
        mkdir ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        mingw32-make
        mv rayjs.exe ..
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rayjs
        path: rayjs.exe
  
  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rayjs
          path: build
